/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ImunisasiAnak;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nsrndv
 */
public class Pendataan extends javax.swing.JFrame {
    
    private String Anak;
    private int Umur;
    private String JK;
    private String Ibu;
    private int HP;
    private String Alamat;
    private int i=1;

//modul 5 class and constructor    
    public Pendataan() {
        initComponents();
        String []book={"No.","Sudah melakukan imunisasi","Demam","Muntah","Nafsu makan menurun","Tubuh lemas","Sakit kepala"};
        DefaultTableModel model = new DefaultTableModel(book,0);
        tabel.setModel(model);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollpanel = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        xAlamat = new javax.swing.JLabel();
        xHP = new javax.swing.JLabel();
        xIbu = new javax.swing.JLabel();
        xJK = new javax.swing.JLabel();
        xUmur = new javax.swing.JLabel();
        xAnak = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        T6 = new javax.swing.JRadioButton();
        F6 = new javax.swing.JRadioButton();
        T5 = new javax.swing.JRadioButton();
        F5 = new javax.swing.JRadioButton();
        T4 = new javax.swing.JRadioButton();
        F4 = new javax.swing.JRadioButton();
        T3 = new javax.swing.JRadioButton();
        F3 = new javax.swing.JRadioButton();
        F2 = new javax.swing.JRadioButton();
        T2 = new javax.swing.JRadioButton();
        F1 = new javax.swing.JRadioButton();
        T1 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        btnhapus = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel.setBackground(new java.awt.Color(204, 255, 255));
        tabel.setForeground(new java.awt.Color(0, 102, 102));
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nomor", "Melakukan imunisasi", "Demam tinggi", "Muntah", "Nafsu makan menurun", "Tubuh lemas", "Sakit kepala"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollpanel.setViewportView(tabel);

        getContentPane().add(scrollpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 55, 630, 90));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Nama");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Umur");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Jenis Kelamin");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Nama Ibu");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("No. Hp");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel13.setText("+62");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jLabel20.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel20.setText("bulan");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        xAlamat.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        xAlamat.setText("_____________");
        getContentPane().add(xAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        xHP.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        xHP.setText("_________");
        getContentPane().add(xHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        xIbu.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        xIbu.setText("_____________");
        getContentPane().add(xIbu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        xJK.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        xJK.setText("_____________");
        getContentPane().add(xJK, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 80, -1));

        xUmur.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        xUmur.setText("___");
        getContentPane().add(xUmur, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 30, -1));

        xAnak.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        xAnak.setText("_____________");
        getContentPane().add(xAnak, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("Sudah melakukan imunisasi?");

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel15.setText("Demam tinggi");

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel16.setText("Muntah");

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel17.setText("Nafsu makan menurun");

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel18.setText("Tubuh lemas");

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel19.setText("Sakit kepala");

        T6.setBackground(new java.awt.Color(204, 255, 255));
        T6.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        T6.setText("Ya");
        T6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T6ActionPerformed(evt);
            }
        });

        F6.setBackground(new java.awt.Color(204, 255, 255));
        F6.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        F6.setText("Tidak");
        F6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F6ActionPerformed(evt);
            }
        });

        T5.setBackground(new java.awt.Color(204, 255, 255));
        T5.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        T5.setText("Ya");
        T5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T5ActionPerformed(evt);
            }
        });

        F5.setBackground(new java.awt.Color(204, 255, 255));
        F5.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        F5.setText("Tidak");
        F5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F5ActionPerformed(evt);
            }
        });

        T4.setBackground(new java.awt.Color(204, 255, 255));
        T4.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        T4.setText("Ya");
        T4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T4ActionPerformed(evt);
            }
        });

        F4.setBackground(new java.awt.Color(204, 255, 255));
        F4.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        F4.setText("Tidak");
        F4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F4ActionPerformed(evt);
            }
        });

        T3.setBackground(new java.awt.Color(204, 255, 255));
        T3.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        T3.setText("Ya");
        T3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T3ActionPerformed(evt);
            }
        });

        F3.setBackground(new java.awt.Color(204, 255, 255));
        F3.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        F3.setText("Tidak");
        F3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F3ActionPerformed(evt);
            }
        });

        F2.setBackground(new java.awt.Color(204, 255, 255));
        F2.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        F2.setText("Tidak");
        F2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F2ActionPerformed(evt);
            }
        });

        T2.setBackground(new java.awt.Color(204, 255, 255));
        T2.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        T2.setText("Ya");
        T2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T2ActionPerformed(evt);
            }
        });

        F1.setBackground(new java.awt.Color(204, 255, 255));
        F1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        F1.setText("Belum");
        F1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F1ActionPerformed(evt);
            }
        });

        T1.setBackground(new java.awt.Color(204, 255, 255));
        T1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        T1.setText("Sudah");
        T1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Apakah anak mengalami gejala ini setelah melakukan imunisasi?");

        btnhapus.setBackground(new java.awt.Color(0, 102, 102));
        btnhapus.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnsimpan.setBackground(new java.awt.Color(0, 102, 102));
        btnsimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(T1)
                        .addGap(10, 10, 10)
                        .addComponent(F1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel14)))
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(T6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel18)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(T4)
                            .addComponent(T3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(T2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(T5, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(F4)
                    .addComponent(F3)
                    .addComponent(F2)
                    .addComponent(F5)
                    .addComponent(F6))
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(T2)
                    .addComponent(F2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(F3)
                            .addComponent(T3)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(F4)
                            .addComponent(T4)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(T5)
                            .addComponent(F5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(F1)
                            .addComponent(T1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(F6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(T6)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnhapus)
                            .addComponent(btnsimpan))
                        .addGap(0, 21, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 163, 630, 240));

        btnclose.setBackground(new java.awt.Color(0, 102, 102));
        btnclose.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnclose.setForeground(new java.awt.Color(255, 255, 255));
        btnclose.setText("X");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 10, 50, 30));

        jLabel9.setFont(new java.awt.Font("Elephant", 0, 36)); // NOI18N
        jLabel9.setText("my");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel10.setFont(new java.awt.Font("Bodoni MT Black", 0, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("IA");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/bggg.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void T1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T1ActionPerformed
        // TODO add your handling code here:
        if(T1.isSelected()){
            F1.setSelected(false);
        }
    }//GEN-LAST:event_T1ActionPerformed

    private void F1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F1ActionPerformed
        // TODO add your handling code here:
        if(F1.isSelected()){
            T1.setSelected(false);
        }
    }//GEN-LAST:event_F1ActionPerformed

    private void T2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T2ActionPerformed
        // TODO add your handling code here:
        if(T2.isSelected()){
            F2.setSelected(false);
        }
    }//GEN-LAST:event_T2ActionPerformed

    private void F2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F2ActionPerformed
        // TODO add your handling code here:
        if(F2.isSelected()){
            T2.setSelected(false);
        }
    }//GEN-LAST:event_F2ActionPerformed

    private void T3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T3ActionPerformed
        // TODO add your handling code here:
        if(T3.isSelected()){
            F3.setSelected(false);
        }
    }//GEN-LAST:event_T3ActionPerformed

    private void F3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F3ActionPerformed
        // TODO add your handling code here:
        if(F3.isSelected()){
            T3.setSelected(false);
        }
    }//GEN-LAST:event_F3ActionPerformed

    private void T4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T4ActionPerformed
        // TODO add your handling code here:
        if(T4.isSelected()){
            F4.setSelected(false);
        }
    }//GEN-LAST:event_T4ActionPerformed

    private void F4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F4ActionPerformed
        // TODO add your handling code here:
        if(F4.isSelected()){
            T4.setSelected(false);
        }
    }//GEN-LAST:event_F4ActionPerformed

    private void T5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T5ActionPerformed
        // TODO add your handling code here:
        if(T5.isSelected()){
            F5.setSelected(false);
        }
    }//GEN-LAST:event_T5ActionPerformed

    private void F5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F5ActionPerformed
        // TODO add your handling code here:
        if(F5.isSelected()){
            T5.setSelected(false);
        }
    }//GEN-LAST:event_F5ActionPerformed

    private void T6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T6ActionPerformed
        // TODO add your handling code here:
        if(T6.isSelected()){
            F6.setSelected(false);
        }
    }//GEN-LAST:event_T6ActionPerformed

    private void F6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F6ActionPerformed
        // TODO add your handling code here:
        if(F6.isSelected()){
            T6.setSelected(false);
        }
    }//GEN-LAST:event_F6ActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
//modul 1 tipe data dan variabel
        String n1 = "-",
               n2 = "-",
               n3 = "-",
               n4 = "-",
               n5 = "-",
               n6 = "-";
//modul 2 pengkondisian if else
//modul 4 fungsi dan method
        if(T1.isSelected()){
            n1 = "Sudah";
        } else if (F1.isSelected()){
            n1 = "Belum";
        }      
        if(T2.isSelected()){
            n2 = "Ya";
        } else if (F2.isSelected()){
            n2 = "Tidak";
        }
        if(T3.isSelected()){
            n3 = "Ya";
        } else if (F3.isSelected()){
            n3 = "Tidak";
        }
        if(T4.isSelected()){
            n4 = "Ya";
        } else if (F4.isSelected()){
            n4 = "Tidak";
        }
        if(T5.isSelected()){
            n5 = "Ya";
        } else if (F5.isSelected()){
            n5 = "Tidak";
        }
        if(T6.isSelected()){
            n6 = "Ya";
        } else if (F6.isSelected()){
            n6 = "Tidak";
        }
 
        if(n1 == "-" || n2 == "-" || n3 == "-" || n4 == "-" || n5 == "-" || n6 == "-"){
           JOptionPane.showMessageDialog(null, "Pastikan kolom terisi semua!"); 
        } else {
            DefaultTableModel model = (DefaultTableModel) tabel.getModel();
            model.addRow(new Object[]{i,n1,n2,n3,n4,n5,n6});
            this.i++;
            setClear();
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showOptionDialog(this, 
                    "Anda yakin ingin menghapus kolom?", 
                    "Hapus", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if(jawab == JOptionPane.YES_OPTION){
            reset();
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null,"Apakah Anda Ingin Keluar?","Peringatan!",JOptionPane.YES_NO_OPTION);
        if(selectedOption == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btncloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pendataan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pendataan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pendataan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pendataan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pendataan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton F1;
    private javax.swing.JRadioButton F2;
    private javax.swing.JRadioButton F3;
    private javax.swing.JRadioButton F4;
    private javax.swing.JRadioButton F5;
    private javax.swing.JRadioButton F6;
    private javax.swing.JRadioButton T1;
    private javax.swing.JRadioButton T2;
    private javax.swing.JRadioButton T3;
    private javax.swing.JRadioButton T4;
    private javax.swing.JRadioButton T5;
    private javax.swing.JRadioButton T6;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane scrollpanel;
    private javax.swing.JTable tabel;
    private javax.swing.JLabel xAlamat;
    private javax.swing.JLabel xAnak;
    private javax.swing.JLabel xHP;
    private javax.swing.JLabel xIbu;
    private javax.swing.JLabel xJK;
    private javax.swing.JLabel xUmur;
    // End of variables declaration//GEN-END:variables

 //modul 6 setter getter
    public void setEt(String anak, int umur, String jenkel, String ibu, int hp, String alamat){
        this.Anak=anak;
        this.Umur=umur;
        this.JK=jenkel;
        this.Ibu=ibu;
        this.HP=hp;
        this.Alamat=alamat;
        
        xAnak.setText(this.Anak);
        xUmur.setText(String.valueOf(this.Umur));
        xJK.setText(this.JK);
        xIbu.setText(this.Ibu);
        xHP.setText(String.valueOf(this.HP));
        xAlamat.setText(this.Alamat);
    }
    
    private void setClear(){
        T1.setSelected(false);
        T2.setSelected(false);
        T3.setSelected(false);
        T4.setSelected(false);
        T5.setSelected(false);
        T6.setSelected(false);
        
        F1.setSelected(false);
        F2.setSelected(false);
        F3.setSelected(false);
        F4.setSelected(false);
        F5.setSelected(false);
        F6.setSelected(false);
    }
    
    private void reset(){
        DefaultTableModel model = (DefaultTableModel) tabel.getModel();
        int row = model.getRowCount();
 //modul 3 perulangan for
        for(int i=row-1;i>=0;i--){           
            model.removeRow(i);
        };
    }
    
}
