/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ImunisasiAnak;

import javax.swing.JOptionPane;

/**
 *
 * @author nsrndv
 */
public class Utama extends javax.swing.JFrame {

    /**
     * Creates new form mainpage
     */
    public Utama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menupanel = new javax.swing.JPanel();
        btnhome = new javax.swing.JLabel();
        btnusia1 = new javax.swing.JLabel();
        btnusia2 = new javax.swing.JLabel();
        btnusia3 = new javax.swing.JLabel();
        btnusia4 = new javax.swing.JLabel();
        btnusia5 = new javax.swing.JLabel();
        btnkalender = new javax.swing.JLabel();
        btndaftar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        mainpanel = new javax.swing.JPanel();
        homepanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnclose = new javax.swing.JButton();
        kalenderpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnclose2 = new javax.swing.JButton();
        usia1panel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnclose3 = new javax.swing.JButton();
        usia2panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnclose4 = new javax.swing.JButton();
        usia3panel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnclose5 = new javax.swing.JButton();
        usia4panel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnclose6 = new javax.swing.JButton();
        usia5panel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnclose7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        menupanel.setBackground(new java.awt.Color(204, 255, 255));

        btnhome.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnhome.setText("Home");
        btnhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhomeMouseClicked(evt);
            }
        });

        btnusia1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnusia1.setText("Usia 0-2 Bulan");
        btnusia1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnusia1MouseClicked(evt);
            }
        });

        btnusia2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnusia2.setText("Usia 3-4 Bulan");
        btnusia2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnusia2MouseClicked(evt);
            }
        });

        btnusia3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnusia3.setText("Usia 6-12 Bulan");
        btnusia3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnusia3MouseClicked(evt);
            }
        });

        btnusia4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnusia4.setText("Usia 15-24 Bulan");
        btnusia4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnusia4MouseClicked(evt);
            }
        });

        btnusia5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnusia5.setText("Usia 3-18 Tahun");
        btnusia5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnusia5MouseClicked(evt);
            }
        });

        btnkalender.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnkalender.setText("Kalender");
        btnkalender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnkalenderMouseClicked(evt);
            }
        });

        btndaftar.setBackground(new java.awt.Color(0, 102, 102));
        btndaftar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btndaftar.setForeground(new java.awt.Color(255, 255, 255));
        btndaftar.setText("DAFTAR IMUNISASI ANAK");
        btndaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndaftarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Elephant", 0, 36)); // NOI18N
        jLabel9.setText("my");

        jLabel10.setFont(new java.awt.Font("Bodoni MT Black", 0, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 153));
        jLabel10.setText("IA");

        jLabel8.setText("          o");

        jLabel11.setText("          o");

        jLabel12.setText("          o");

        jLabel13.setText("          o");

        jLabel14.setText("          o");

        javax.swing.GroupLayout menupanelLayout = new javax.swing.GroupLayout(menupanel);
        menupanel.setLayout(menupanelLayout);
        menupanelLayout.setHorizontalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menupanelLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnhome)
                            .addComponent(btnkalender)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menupanelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))))
                    .addGroup(menupanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btndaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menupanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnusia5)
                            .addComponent(btnusia2)
                            .addComponent(btnusia1)
                            .addComponent(btnusia3)
                            .addComponent(btnusia4))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        menupanelLayout.setVerticalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(40, 40, 40)
                .addComponent(btnhome)
                .addGap(18, 18, 18)
                .addComponent(btnkalender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnusia1)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnusia2)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnusia3)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnusia4)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnusia5)
                    .addComponent(jLabel14))
                .addGap(43, 43, 43)
                .addComponent(btndaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainpanel.setBackground(new java.awt.Color(255, 255, 255));
        mainpanel.setLayout(new java.awt.CardLayout());

        homepanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/imunisasi.jpg"))); // NOI18N

        btnclose.setBackground(new java.awt.Color(0, 102, 102));
        btnclose.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnclose.setForeground(new java.awt.Color(255, 255, 255));
        btnclose.setText("X");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homepanelLayout = new javax.swing.GroupLayout(homepanel);
        homepanel.setLayout(homepanelLayout);
        homepanelLayout.setHorizontalGroup(
            homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homepanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        homepanelLayout.setVerticalGroup(
            homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        mainpanel.add(homepanel, "card2");

        kalenderpanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/kalender1.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("KALENDER IMUNISASI ANAK");

        btnclose2.setBackground(new java.awt.Color(0, 102, 102));
        btnclose2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnclose2.setForeground(new java.awt.Color(255, 255, 255));
        btnclose2.setText("X");
        btnclose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclose2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kalenderpanelLayout = new javax.swing.GroupLayout(kalenderpanel);
        kalenderpanel.setLayout(kalenderpanelLayout);
        kalenderpanelLayout.setHorizontalGroup(
            kalenderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kalenderpanelLayout.createSequentialGroup()
                .addGroup(kalenderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kalenderpanelLayout.createSequentialGroup()
                        .addGroup(kalenderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kalenderpanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel2))
                            .addGroup(kalenderpanelLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jLabel3)))
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kalenderpanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnclose2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        kalenderpanelLayout.setVerticalGroup(
            kalenderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kalenderpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnclose2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(86, 86, 86))
        );

        mainpanel.add(kalenderpanel, "card3");

        usia1panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/0-2 bulan.jpg"))); // NOI18N

        btnclose3.setBackground(new java.awt.Color(0, 102, 102));
        btnclose3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnclose3.setForeground(new java.awt.Color(255, 255, 255));
        btnclose3.setText("X");
        btnclose3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclose3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout usia1panelLayout = new javax.swing.GroupLayout(usia1panel);
        usia1panel.setLayout(usia1panelLayout);
        usia1panelLayout.setHorizontalGroup(
            usia1panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usia1panelLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(usia1panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usia1panelLayout.createSequentialGroup()
                        .addComponent(btnclose3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usia1panelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(65, 65, 65))))
        );
        usia1panelLayout.setVerticalGroup(
            usia1panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usia1panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnclose3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(80, 80, 80))
        );

        mainpanel.add(usia1panel, "card4");

        usia2panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/3-4 bulan.jpg"))); // NOI18N

        btnclose4.setBackground(new java.awt.Color(0, 102, 102));
        btnclose4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnclose4.setForeground(new java.awt.Color(255, 255, 255));
        btnclose4.setText("X");
        btnclose4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclose4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout usia2panelLayout = new javax.swing.GroupLayout(usia2panel);
        usia2panel.setLayout(usia2panelLayout);
        usia2panelLayout.setHorizontalGroup(
            usia2panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usia2panelLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(usia2panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usia2panelLayout.createSequentialGroup()
                        .addComponent(btnclose4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usia2panelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(64, 64, 64))))
        );
        usia2panelLayout.setVerticalGroup(
            usia2panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usia2panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnclose4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel5)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        mainpanel.add(usia2panel, "card5");

        usia3panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/6-12 bulan.jpg"))); // NOI18N

        btnclose5.setBackground(new java.awt.Color(0, 102, 102));
        btnclose5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnclose5.setForeground(new java.awt.Color(255, 255, 255));
        btnclose5.setText("X");
        btnclose5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclose5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout usia3panelLayout = new javax.swing.GroupLayout(usia3panel);
        usia3panel.setLayout(usia3panelLayout);
        usia3panelLayout.setHorizontalGroup(
            usia3panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usia3panelLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(usia3panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usia3panelLayout.createSequentialGroup()
                        .addComponent(btnclose5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usia3panelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(66, 66, 66))))
        );
        usia3panelLayout.setVerticalGroup(
            usia3panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usia3panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnclose5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel6)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        mainpanel.add(usia3panel, "card6");

        usia4panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/15-24 bulan.jpg"))); // NOI18N

        btnclose6.setBackground(new java.awt.Color(0, 102, 102));
        btnclose6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnclose6.setForeground(new java.awt.Color(255, 255, 255));
        btnclose6.setText("X");
        btnclose6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclose6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout usia4panelLayout = new javax.swing.GroupLayout(usia4panel);
        usia4panel.setLayout(usia4panelLayout);
        usia4panelLayout.setHorizontalGroup(
            usia4panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usia4panelLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(usia4panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usia4panelLayout.createSequentialGroup()
                        .addComponent(btnclose6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usia4panelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(66, 66, 66))))
        );
        usia4panelLayout.setVerticalGroup(
            usia4panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usia4panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnclose6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(70, 70, 70))
        );

        mainpanel.add(usia4panel, "card7");

        usia5panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/3-18 tahun.jpg"))); // NOI18N

        btnclose7.setBackground(new java.awt.Color(0, 102, 102));
        btnclose7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnclose7.setForeground(new java.awt.Color(255, 255, 255));
        btnclose7.setText("X");
        btnclose7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclose7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout usia5panelLayout = new javax.swing.GroupLayout(usia5panel);
        usia5panel.setLayout(usia5panelLayout);
        usia5panelLayout.setHorizontalGroup(
            usia5panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usia5panelLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(usia5panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usia5panelLayout.createSequentialGroup()
                        .addComponent(btnclose7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usia5panelLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(67, 67, 67))))
        );
        usia5panelLayout.setVerticalGroup(
            usia5panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usia5panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnclose7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel15)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        mainpanel.add(usia5panel, "card8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(menupanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menupanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(835, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomeMouseClicked
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();

        mainpanel.add(homepanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_btnhomeMouseClicked

    private void btnusia1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnusia1MouseClicked
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();

        mainpanel.add(usia1panel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_btnusia1MouseClicked

    private void btnusia2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnusia2MouseClicked
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();

        mainpanel.add(usia2panel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_btnusia2MouseClicked

    private void btnusia3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnusia3MouseClicked
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();

        mainpanel.add(usia3panel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_btnusia3MouseClicked

    private void btnusia4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnusia4MouseClicked
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();

        mainpanel.add(usia4panel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_btnusia4MouseClicked

    private void btnusia5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnusia5MouseClicked
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();

        mainpanel.add(usia5panel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_btnusia5MouseClicked

    private void btnkalenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkalenderMouseClicked
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();

        mainpanel.add(kalenderpanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_btnkalenderMouseClicked

    private void btndaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndaftarActionPerformed
        dispose();
        Pendaftaran a = new Pendaftaran();
        a.setVisible(true);
    }//GEN-LAST:event_btndaftarActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null,"Apakah Anda Ingin Keluar?","Peringatan!",JOptionPane.YES_NO_OPTION);
        if(selectedOption == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnclose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclose2ActionPerformed
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null,"Apakah Anda Ingin Keluar?","Peringatan!",JOptionPane.YES_NO_OPTION);
        if(selectedOption == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnclose2ActionPerformed

    private void btnclose3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclose3ActionPerformed
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null,"Apakah Anda Ingin Keluar?","Peringatan!",JOptionPane.YES_NO_OPTION);
        if(selectedOption == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnclose3ActionPerformed

    private void btnclose4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclose4ActionPerformed
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null,"Apakah Anda Ingin Keluar?","Peringatan!",JOptionPane.YES_NO_OPTION);
        if(selectedOption == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnclose4ActionPerformed

    private void btnclose5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclose5ActionPerformed
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null,"Apakah Anda Ingin Keluar?","Peringatan!",JOptionPane.YES_NO_OPTION);
        if(selectedOption == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnclose5ActionPerformed

    private void btnclose6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclose6ActionPerformed
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null,"Apakah Anda Ingin Keluar?","Peringatan!",JOptionPane.YES_NO_OPTION);
        if(selectedOption == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnclose6ActionPerformed

    private void btnclose7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclose7ActionPerformed
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null,"Apakah Anda Ingin Keluar?","Peringatan!",JOptionPane.YES_NO_OPTION);
        if(selectedOption == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnclose7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnclose2;
    private javax.swing.JButton btnclose3;
    private javax.swing.JButton btnclose4;
    private javax.swing.JButton btnclose5;
    private javax.swing.JButton btnclose6;
    private javax.swing.JButton btnclose7;
    private javax.swing.JButton btndaftar;
    private javax.swing.JLabel btnhome;
    private javax.swing.JLabel btnkalender;
    private javax.swing.JLabel btnusia1;
    private javax.swing.JLabel btnusia2;
    private javax.swing.JLabel btnusia3;
    private javax.swing.JLabel btnusia4;
    private javax.swing.JLabel btnusia5;
    private javax.swing.JPanel homepanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel kalenderpanel;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel menupanel;
    private javax.swing.JPanel usia1panel;
    private javax.swing.JPanel usia2panel;
    private javax.swing.JPanel usia3panel;
    private javax.swing.JPanel usia4panel;
    private javax.swing.JPanel usia5panel;
    // End of variables declaration//GEN-END:variables
}
